version: '3.9'
services:
  PostgreSQLContainer:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zCGHq3
      - POSTGRES_DB=hendelser